name: Scrape Japan Hotel

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  USER_AGENT: ${{ secrets.USER_AGENT }}

jobs:
  scrape-latest:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Japan Scraper
        run: python automated_scraper.py --japan=True

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: './'
          destination: 'japan_hotels'
          glob: 'scraped_japan_hotel_data_csv/*.csv'


